version: '2'
services:

  fluentd:
    container_name: fluentd
    image: fluentd-demo
    volumes:
      - $PWD/:/fluentd/etc
    ports:
      - "24224:24224"

  httpd:
    container_name: httpd
    image: httpd-demo
    ports:
      - "80:80"
    links:
      - fluentd      
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access