version: '2'
services:

  fluentd:
    container_name: fluentd
    image: fluentd-demo
    volumes:
      - $PWD/:/fluentd/etc
    links:
      - elasticsearch
    ports:
      - "24224:24224"

  spring-boot-fluentd-demo:
    container_name: spring-boot-fluentd-demo
    image: spring-boot-fluentd-demo
    ports:
      - "8080:8080"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: springboot.demo.fluentd


  httpd:
    container_name: httpd
    image: http-demo
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: kibana
    links:
      - elasticsearch
    ports:
      - "5601:5601"