version: '2'
services:

  fluentd:
    container_name: fluentd
    image: fluentd-demo
    volumes:
      - $PWD/:/fluentd/etc
    ports:
      - "24224:24224"
      
  echo:
    container_name: echo
    image: debian
    command: bash -c 'for((i=1;i<=1000;i+=1)); do echo -e "Welcome $${i} times"; sleep 2; done;'
    links:
      - fluentd  
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: echo